/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditMeetingNumberRouteImport } from './routes/edit.$meeting.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditMeetingNumberRoute = EditMeetingNumberRouteImport.update({
  id: '/edit/$meeting/$number',
  path: '/edit/$meeting/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit/$meeting/$number': typeof EditMeetingNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit/$meeting/$number': typeof EditMeetingNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit/$meeting/$number': typeof EditMeetingNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edit/$meeting/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit/$meeting/$number'
  id: '__root__' | '/' | '/edit/$meeting/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditMeetingNumberRoute: typeof EditMeetingNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$meeting/$number': {
      id: '/edit/$meeting/$number'
      path: '/edit/$meeting/$number'
      fullPath: '/edit/$meeting/$number'
      preLoaderRoute: typeof EditMeetingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditMeetingNumberRoute: EditMeetingNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
